FROM node:20-alpine AS build
WORKDIR /app
COPY backend/package*.json ./
COPY backend/prisma ./prisma/
RUN npm install
COPY backend/ ./
RUN npx prisma generate
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/package*.json ./
COPY --from=build /app/dist ./dist
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/src ./src
COPY --from=build /app/node_modules ./node_modules
ENV PORT=5000
EXPOSE 5000
CMD ["sh", "-c", "npx prisma db push && npx ts-node src/seed.ts && npm start"]
