FROM node:20-alpine
WORKDIR /app
COPY backend/package*.json ./
COPY backend/prisma ./prisma/
RUN npm install
COPY backend/ ./
RUN npx prisma generate

ENV PORT=5000
EXPOSE 5000
CMD ["sh", "-c", "npx prisma db push && npx ts-node src/seed.ts && npx ts-node src/server.ts"]
